version: '3'

networks:
  ctf-net:
    driver: bridge

services:
  db:
    restart: unless-stopped
    image: postgres:latest
    container_name: db
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    networks:
      - ctf-net
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=plzchange
      - POSTGRES_DB=postgres

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - ctf-net
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=plzchange
      - POSTGRES_DB=postgres
      - SQL_HOST=db
    depends_on:
      - db

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./testing/nginix/frontend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ctf-net

  proxy:
    restart: unless-stopped
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./testing/nginix/proxy.conf:/etc/nginx/conf.d/default.conf
      # CERTS 
      #- .certs/-:/etc/nginx/conf.d/default.conf
      #- ./testing/nginix/proxyssl.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ctf-net
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend