version: '3'

networks:
  ctf-net:
    driver: bridge

services:
  db:
    restart: unless-stopped
    image: postgres:latest
    container_name: db
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    networks:
      - ctf-net
    environment:
      - POSTGRES_DB=yacf
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=plzchange

  server:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server
    networks:
      - ctf-net
    environment:
      - DEBUGGER=True
      - APP_KEY="plzchange"
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=plzchange
      - POSTGRES_DB=postgres
      - SQL_HOST=db
    depends_on:
      - db

  client:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client
    volumes:
      - ./confs/nginix/frontend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ctf-net

  proxy:
    restart: unless-stopped
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./confs/nginix/proxy.conf:/etc/nginx/conf.d/default.conf
      # CERTS 
      #- .certs/-:etc/nginx/ssl/
      #- ./confs/nginix/sslproxy.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ctf-net
    ports:
      - "80:80"
      #- "443:443"
    depends_on:
      - server
      - client