# Generated by Django 2.1.8 on 2019-12-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegisterKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('singleuse', models.BooleanField()),
                ('expiration', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
