# Generated by Django 2.1.8 on 2019-12-11 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0003_logintracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to=settings.AUTH_USER_MODEL),
        ),
    ]
