# Generated by Django 2.1.8 on 2019-12-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='encode',
            field=models.BooleanField(default=False),
        ),
    ]
