# Generated by Django 2.1.8 on 2019-12-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_encode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='encode',
            new_name='encoded',
        ),
    ]
