# Generated by Django 2.1.8 on 2019-12-08 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20191203_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='algorithm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hash', to='challenges.Hash'),
        ),
    ]
