# Generated by Django 2.1.8 on 2019-12-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20191208_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
