version: '3'

services:
  redis:
    restart: always
    image: redis:5.0.1
    hostname: redis-broker
    ports:
      - "6379:6379"
  
  yacf:
    restart: always
    image: 0xcodes/yacf:0.1-beta
    hostname: yacf.0x.codes
    ports:
      - "80:80"
    links:
      - redis